# Generated by Django 3.1.3 on 2020-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
